persistence: "POSTGRESQLDETTES"

repo: "RepositoryList"
repositories:
  RepositoryJPA: "com.ism.core.Factory.FactoryRepositoryJPA"
  RepositoryBD: "com.ism.core.Factory.FactoryRepositoryBD"
  RepositoryList: "com.ism.core.Factory.FactoryRepositoryList"

connection:
  type: "postgres" 
  mysql:
    url: "jdbc:mysql://localhost:3306/gestion_boutique"
    user : "root"
    password: ""
    driver: "com.mysql.cj.jdbc.Driver"
  postgres:
    url: "jdbc:postgresql://localhost:5432/gestion_boutique"
    user: "postgres"
    password: "008088"
    driver: "org.postgresql.Driver"

